require('dotenv').config();

export interface IEnvConfig {
  DOMAIN: string
  CLIENT_ID: string
  CLIENT_SECRET: string
  SAML_SP_DOMAIN: string
  SAML_SP_CLIENT_ID: string
  SAML_SP_CLIENT_SECRET: string
  MOBILE_IOS_CALLBACK: string[]
  MOBILE_ANDROID_CALLBACK: string[]
  MOBILE_IOS_LOGOUT: string[]
  CLOUDFLARE_ZONE_ID: string
  CLOUDFLARE_API_TOKEN: string
  AWS_ACCESS_KEY_ID: string
  AWS_ACCESS_SECRET_KEY: string
  AWS_REGION: string
  GUARDIAN_SNS_GCM_PLATFORM_APP_ARN: string
  GUARDIAN_SNS_APNS_PLATFORM_APP_ARN: string
  GUARDIAN_SNS_GCM_SERVER_KEY: string
  GUARDIAN_SNS_EVENT_DELIVERY_EMAIL: string
  LOG_STREAM_AWS_ACCOUNT_ID: string
  PROTOCOL_DEBUGGER_CALLBACK: string
}

export const envConfig: IEnvConfig = {
  DOMAIN: process.env.DOMAIN!,
  CLIENT_ID: process.env.CLIENT_ID!,
  CLIENT_SECRET: process.env.CLIENT_SECRET!,
  SAML_SP_DOMAIN: process.env.SAML_SP_DOMAIN!,
  SAML_SP_CLIENT_ID: process.env.SAML_SP_CLIENT_ID!,
  SAML_SP_CLIENT_SECRET: process.env.SAML_SP_CLIENT_SECRET!,
  MOBILE_IOS_CALLBACK: process.env.MOBILE_IOS_CALLBACK?.split(",") || [],
  MOBILE_ANDROID_CALLBACK: process.env.MOBILE_ANDROID_CALLBACK?.split(",") || [],
  MOBILE_IOS_LOGOUT: process.env.MOBILE_IOS_LOGOUT?.split(",") || [],
  CLOUDFLARE_ZONE_ID: process.env.CLOUDFLARE_ZONE_ID!,
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN!,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID!,
  AWS_ACCESS_SECRET_KEY: process.env.AWS_ACCESS_SECRET_KEY!,
  AWS_REGION: process.env.AWS_REGION!,
  GUARDIAN_SNS_GCM_PLATFORM_APP_ARN: process.env.GUARDIAN_SNS_GCM_PLATFORM_APP_ARN!,
  GUARDIAN_SNS_APNS_PLATFORM_APP_ARN: process.env.GUARDIAN_SNS_APNS_PLATFORM_APP_ARN!,
  GUARDIAN_SNS_GCM_SERVER_KEY: process.env.GUARDIAN_SNS_GCM_SERVER_KEY!,
  GUARDIAN_SNS_EVENT_DELIVERY_EMAIL: process.env.GUARDIAN_SNS_EVENT_DELIVERY_EMAIL!,
  LOG_STREAM_AWS_ACCOUNT_ID: process.env.LOG_STREAM_AWS_ACCOUNT_ID!,
  PROTOCOL_DEBUGGER_CALLBACK: process.env.PROTOCOL_DEBUGGER_CALLBACK!
} 