require('dotenv').config();

export interface IEnvConfig {
  DOMAIN: string
  CLIENT_ID: string
  CLIENT_SECRET: string
  CUSTOM_DOMAIN: string
  CUSTOM_DOMAIN_ETLD: string
  SAML_SP_DOMAIN: string
  SAML_SP_CLIENT_ID: string
  SAML_SP_CLIENT_SECRET: string
  MOBILE_IOS_CALLBACK: string[]
  MOBILE_ANDROID_CALLBACK: string[]
  MOBILE_IOS_LOGOUT: string[]
  CLOUDFLARE_ZONE_ID: string
  CLOUDFLARE_API_TOKEN: string
  AWS_ACCESS_KEY_ID: string
  AWS_ACCESS_SECRET_KEY: string
  AWS_REGION: string
  GUARDIAN_SNS_GCM_PLATFORM_APP_ARN: string
  GUARDIAN_SNS_APNS_PLATFORM_APP_ARN: string
  GUARDIAN_SNS_GCM_SERVER_KEY: string
  GUARDIAN_SNS_EVENT_DELIVERY_EMAIL: string
  LOG_STREAM_AWS_ACCOUNT_ID: string
  SMTP_HOST: string
  SMTP_PORT: string
  SMTP_AUTH_USER: string
  SMTP_AUTH_PASS: string
  PASSWORDLESS_SMS_USER_PHONE_NUMBER: string
  PASSWORDLESS_SMS_SEND_FROM_NUMBER: string
  TWILIO_SID: string
  TWILIO_TOKEN: string
  AZUREAD_TENANT_ID: string
  AZUREAD_CLIENT_ID: string
  AZUREAD_CLIENT_SECRET: string
  GOOGLE_CIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  PROTOCOL_DEBUGGER_CALLBACK: string
}

export const envConfig: IEnvConfig = {
  DOMAIN: process.env.DOMAIN!,
  CLIENT_ID: process.env.CLIENT_ID!,
  CLIENT_SECRET: process.env.CLIENT_SECRET!,
  CUSTOM_DOMAIN: process.env.CUSTOM_DOMAIN!,
  CUSTOM_DOMAIN_ETLD: process.env.CUSTOM_DOMAIN_ETLD!,
  SAML_SP_DOMAIN: process.env.SAML_SP_DOMAIN!,
  SAML_SP_CLIENT_ID: process.env.SAML_SP_CLIENT_ID!,
  SAML_SP_CLIENT_SECRET: process.env.SAML_SP_CLIENT_SECRET!,
  MOBILE_IOS_CALLBACK: process.env.MOBILE_IOS_CALLBACK?.split(",") || [],
  MOBILE_ANDROID_CALLBACK: process.env.MOBILE_ANDROID_CALLBACK?.split(",") || [],
  MOBILE_IOS_LOGOUT: process.env.MOBILE_IOS_LOGOUT?.split(",") || [],
  CLOUDFLARE_ZONE_ID: process.env.CLOUDFLARE_ZONE_ID!,
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN!,
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID!,
  AWS_ACCESS_SECRET_KEY: process.env.AWS_ACCESS_SECRET_KEY!,
  AWS_REGION: process.env.AWS_REGION!,
  GUARDIAN_SNS_GCM_PLATFORM_APP_ARN: process.env.GUARDIAN_SNS_GCM_PLATFORM_APP_ARN!,
  GUARDIAN_SNS_APNS_PLATFORM_APP_ARN: process.env.GUARDIAN_SNS_APNS_PLATFORM_APP_ARN!,
  GUARDIAN_SNS_GCM_SERVER_KEY: process.env.GUARDIAN_SNS_GCM_SERVER_KEY!,
  GUARDIAN_SNS_EVENT_DELIVERY_EMAIL: process.env.GUARDIAN_SNS_EVENT_DELIVERY_EMAIL!,
  LOG_STREAM_AWS_ACCOUNT_ID: process.env.LOG_STREAM_AWS_ACCOUNT_ID!,
  SMTP_HOST: process.env.SMTP_HOST!,
  SMTP_PORT: process.env.SMTP_PORT!,
  SMTP_AUTH_USER: process.env.SMTP_AUTH_USER!,
  SMTP_AUTH_PASS: process.env.SMTP_AUTH_PASS!,
  PASSWORDLESS_SMS_USER_PHONE_NUMBER: process.env.PASSWORDLESS_SMS_USER_PHONE_NUMBER!,
  PASSWORDLESS_SMS_SEND_FROM_NUMBER: process.env.PASSWORDLESS_SMS_SEND_FROM_NUMBER!,
  TWILIO_SID: process.env.TWILIO_SID!,
  TWILIO_TOKEN: process.env.TWILIO_TOKEN!,
  AZUREAD_TENANT_ID: process.env.AZUREAD_TENANT_ID!,
  AZUREAD_CLIENT_ID: process.env.AZUREAD_CLIENT_ID!,
  AZUREAD_CLIENT_SECRET: process.env.AZUREAD_CLIENT_SECRET!,
  GOOGLE_CIENT_ID: process.env.GOOGLE_CIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  PROTOCOL_DEBUGGER_CALLBACK: process.env.PROTOCOL_DEBUGGER_CALLBACK!
} 